**Python Basics**

In [1]:
# --- LOOPS ---
print("--- LOOPS ---")

# 1. For Loop
print("For Loop:")
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)

# 2. While Loop
print("\nWhile Loop:")
count = 0
while count < 3:
    print(f"Count is {count}")
    count += 1

# --- FUNCTIONS ---
print("\n--- FUNCTIONS ---")

# 1. Simple Function
def greet():
    print("Hello from a function!")
greet()

# 2. Function with Arguments
def add_numbers(a, b):
    return a + b
result = add_numbers(5, 10)
print(f"Sum function result: {result}")

# 3. Lambda Function (Anonymous)
square = lambda x: x * x
print(f"Lambda square of 4: {square(4)}")

# --- LISTS (10 Methods) ---
print("\n--- LISTS ---")
my_list = [10, 20, 30]

# 1. append(): Adds an element at the end
my_list.append(40)
print(f"1. Append: {my_list}")

# 2. extend(): Add multiple elements
my_list.extend([50, 60])
print(f"2. Extend: {my_list}")

# 3. insert(): Insert at a specific position (index 1)
my_list.insert(1, 15)
print(f"3. Insert: {my_list}")

# 4. remove(): Removes the first item with the specified value
my_list.remove(15)
print(f"4. Remove: {my_list}")

# 5. pop(): Removes the element at the specified position
my_list.pop(0)
print(f"5. Pop: {my_list}")

# 6. index(): Returns the index of the first element with the specified value
idx = my_list.index(50)
print(f"6. Index of 50: {idx}")

# 7. count(): Returns the number of elements with the specified value
count_20 = my_list.count(20)
print(f"7. Count of 20: {count_20}")

# 8. reverse(): Reverses the order of the list
my_list.reverse()
print(f"8. Reverse: {my_list}")

# 9. sort(): Sorts the list
my_list.sort()
print(f"9. Sort: {my_list}")

# 10. clear(): Removes all the elements from the list
my_list.clear()
print(f"10. Clear: {my_list}")

# --- DICTIONARIES ---
print("\n--- DICTIONARIES ---")

# List to Dictionary
keys = ["name", "age", "city"]
values = ["Hamna", 21, "Lahore"]
my_dict = dict(zip(keys, values))
print(f"List to Dict: {my_dict}")

# Dictionary to List of Tuples
dict_items = list(my_dict.items())
print(f"Dict to List (Tuples): {dict_items}")

# Accessing keys only
keys_list = list(my_dict.keys())
print(f"Keys only: {keys_list}")

--- LOOPS ---
For Loop:
apple
banana
cherry

While Loop:
Count is 0
Count is 1
Count is 2

--- FUNCTIONS ---
Hello from a function!
Sum function result: 15
Lambda square of 4: 16

--- LISTS ---
1. Append: [10, 20, 30, 40]
2. Extend: [10, 20, 30, 40, 50, 60]
3. Insert: [10, 15, 20, 30, 40, 50, 60]
4. Remove: [10, 20, 30, 40, 50, 60]
5. Pop: [20, 30, 40, 50, 60]
6. Index of 50: 3
7. Count of 20: 1
8. Reverse: [60, 50, 40, 30, 20]
9. Sort: [20, 30, 40, 50, 60]
10. Clear: []

--- DICTIONARIES ---
List to Dict: {'name': 'Hamna', 'age': 21, 'city': 'Lahore'}
Dict to List (Tuples): [('name', 'Hamna'), ('age', 21), ('city', 'Lahore')]
Keys only: ['name', 'age', 'city']


**NumPy**

In [2]:
import numpy as np

# --- ARRAYS ---
print("--- NUMPY ARRAYS ---")
# 1D Array
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr_1d}")

# 2D Array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D Array:\n{arr_2d}")

# --- VECTORIZED OPERATIONS ---
print("\n--- VECTORIZED OPERATIONS ---")
# Operations are applied element-wise without loops
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

add = a + b
print(f"Addition (a+b): {add}")

mult = a * b
print(f"Multiplication (a*b): {mult}")

power = a ** 2
print(f"Squaring (a^2): {power}")

--- NUMPY ARRAYS ---
1D Array: [1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]]

--- VECTORIZED OPERATIONS ---
Addition (a+b): [11 22 33]
Multiplication (a*b): [10 40 90]
Squaring (a^2): [100 400 900]


**Matrix Operations**

In [3]:
# --- MATRIX MULTIPLICATION ---
print("--- MATRIX MULTIPLICATION ---")
# Matrix A (2x3)
mat_a = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Matrix B (3x2) - Needed for dot product
mat_b = np.array([[7, 8],
                  [9, 1],
                  [2, 3]])

# Using np.dot()
product_1 = np.dot(mat_a, mat_b)
print(f"Dot Product (Method 1):\n{product_1}")

# Using @ operator
product_2 = mat_a @ mat_b
print(f"Dot Product (Method 2):\n{product_2}")

# --- BROADCASTING ---
print("\n--- BROADCASTING ---")

# Broadcasting allows operations on arrays of different shapes
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
scalar = 10

# Adding a scalar to a matrix (Scalar is "broadcast" to all elements)
broadcast_result = matrix + scalar
print(f"Original Matrix:\n{matrix}")
print(f"Broadcasting (+10):\n{broadcast_result}")

# Broadcasting a row to a matrix
row = np.array([1, 0, 1])
row_broadcast = matrix + row
print(f"Row Broadcasting (+ [1,0,1]):\n{row_broadcast}")

--- MATRIX MULTIPLICATION ---
Dot Product (Method 1):
[[31 19]
 [85 55]]
Dot Product (Method 2):
[[31 19]
 [85 55]]

--- BROADCASTING ---
Original Matrix:
[[1 2 3]
 [4 5 6]]
Broadcasting (+10):
[[11 12 13]
 [14 15 16]]
Row Broadcasting (+ [1,0,1]):
[[2 2 4]
 [5 5 7]]
